#!/bin/bash

set -e -o pipefail

BASE=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

DISTRIB=
DISTRIB_RELEASE=

if [ "$(uname -s)" = "Darwin" ]; then
	DISTRIB=macOS
else
	if [ -f /etc/os-release ]; then
		. /etc/os-release
		DISTRIB=$ID
		DISTRIB_RELEASE=$VERSION_ID
	elif [ -f /etc/lsb-release ]; then
		DISTRIB=$(cat /etc/lsb-release | grep "DISTRIB_ID" | awk -F "=" '{print $2}')
		DISTRIB_RELEASE=$(cat /etc/lsb-release | grep "DISTRIB_RELEASE" | awk -F "=" '{print $2}')
	fi
fi

FLASH_TOOL="$BASE/flash-tool"
KHADAS_TOOL="$BASE/aml-burn-tool"
RULES_DIR="$BASE/rules"
INSTALL_DIR="/usr/local/bin"

RULE=

RED='\033[0;31m'
YELLOW="\e[0;33m"
RESET='\033[m'

echo ""
echo "==============================================="
echo ""
echo "Host PC: $DISTRIB $DISTRIB_RELEASE"
echo ""
echo "==============================================="
echo ""

error_msg() {
	echo -e ${RED}Error:${RESET} $1
}

warning_msg() {
	echo -e ${YELLOW}Warning:${RESET} $1
}

if [ "$DISTRIB" != "ubuntu" ] && [ "$DISTRIB" != "debian" ] && [ "$DISTRIB" != "raspbian" ] && [ "$DISTRIB" != "macOS" ]; then
	warning_msg "This flash tool is only verified on Ubuntu, Debian, and Raspbian. Your distribution ($DISTRIB) is not officially supported and the installation may fail."
fi

if [ "$DISTRIB" != "macOS" ]; then
	echo "Installing USB rules..."

	RULE="$RULES_DIR/70-persistent-usb-ubuntu14.rules"
	sudo cp $RULE /etc/udev/rules.d

	sudo udevadm control --reload-rules
fi

echo "Installing flash-tool..."
mkdir -p $INSTALL_DIR
sudo ln -fs $KHADAS_TOOL $INSTALL_DIR/$(basename $KHADAS_TOOL)

echo "Done!"